################################################################################
# Automatically-generated file. Do not edit!
################################################################################

C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
CC_SRCS := 
ASM_SRCS := 
C_SRCS := 
CPP_SRCS := 
O_SRCS := 
S_UPPER_SRCS := 
CC_DEPS := 
C++_DEPS := 
EXECUTABLES := 
OBJS := 
C_UPPER_DEPS := 
CXX_DEPS := 
C_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
utils \
src/wimax/test \
src/wimax/model \
src/wimax/helper \
src/wimax/examples \
src/wifi/test \
src/wifi/model \
src/wifi/helper \
src/wifi/examples \
src/wave/test \
src/wave/model \
src/wave/helper \
src/wave/examples \
src/visualizer/model \
src/virtual-net-device/model \
src/virtual-net-device/examples \
src/uan/test \
src/uan/model \
src/uan/helper \
src/uan/examples \
src/topology-read/test \
src/topology-read/model \
src/topology-read/helper \
src/topology-read/examples \
src/test/perf \
src/test/ns3wifi \
src/test/ns3tcp \
src/test \
src/tap-bridge/model \
src/tap-bridge/helper \
src/tap-bridge/examples \
src/stats/test \
src/stats/model \
src/stats/helper \
src/stats/examples \
src/spectrum/test \
src/spectrum/model \
src/spectrum/helper \
src/spectrum/examples \
src/sixlowpan/test \
src/sixlowpan/model \
src/sixlowpan/helper \
src/sixlowpan/examples \
src/propagation/test \
src/propagation/model \
src/propagation/examples \
src/point-to-point-layout/model \
src/point-to-point/test \
src/point-to-point/model \
src/point-to-point/helper \
src/point-to-point/examples \
src/openflow/test \
src/openflow/model \
src/openflow/helper \
src/openflow/examples \
src/olsr/test \
src/olsr/model \
src/olsr/helper \
src/olsr/examples \
src/nix-vector-routing/model \
src/nix-vector-routing/helper \
src/nix-vector-routing/examples \
src/network/utils \
src/network/test \
src/network/model \
src/network/helper \
src/network/examples \
src/netanim/test \
src/netanim/model \
src/netanim/examples \
src/mpi/model \
src/mpi/examples \
src/mobility/test \
src/mobility/model \
src/mobility/helper \
src/mobility/examples \
src/mesh/test \
src/mesh/test/flame \
src/mesh/test/dot11s \
src/mesh/model \
src/mesh/model/flame \
src/mesh/model/dot11s \
src/mesh/helper \
src/mesh/helper/flame \
src/mesh/helper/dot11s \
src/mesh/examples \
src/lte/test \
src/lte/model \
src/lte/helper \
src/lte/examples \
src/lr-wpan/test \
src/lr-wpan/model \
src/lr-wpan/helper \
src/lr-wpan/examples \
src/internet/test \
src/internet/model \
src/internet/helper \
src/internet/examples \
src/flow-monitor/test \
src/flow-monitor/model \
src/flow-monitor/helper \
src/fd-net-device/model \
src/fd-net-device/helper \
src/fd-net-device/examples \
src/energy/test \
src/energy/model \
src/energy/helper \
src/energy/examples \
src/dsr/test \
src/dsr/model \
src/dsr/helper \
src/dsr/examples \
src/dsdv/test \
src/dsdv/model \
src/dsdv/helper \
src/dsdv/examples \
src/csma-layout/model \
src/csma-layout/examples \
src/csma/model \
src/csma/helper \
src/csma/examples \
src/core/test \
src/core/model \
src/core/helper \
src/core/examples \
src/core/bindings \
src/config-store/model \
src/config-store/examples \
src/click/test \
src/click/model \
src/click/helper \
src/click/examples \
src/buildings/test \
src/buildings/model \
src/buildings/helper \
src/buildings/examples \
src/brite/test \
src/brite/helper \
src/brite/examples \
src/bridge/model \
src/bridge/helper \
src/bridge/examples \
src/applications/test \
src/applications/model \
src/applications/helper \
src/aodv/test \
src/aodv/model \
src/aodv/helper \
src/aodv/examples \
src/antenna/test \
src/antenna/model \
scratch/subdir \
scratch \
examples/wireless \
examples/udp-client-server \
examples/udp \
examples/tutorial \
examples/tcp \
examples/stats \
examples/socket \
examples/routing \
examples/realtime \
examples/naming \
examples/matrix-topology \
examples/ipv6 \
examples/error-model \
examples/energy \
build/utils \
build/src/wimax/test \
build/src/wimax/model \
build/src/wimax/helper \
build/src/wimax/examples \
build/src/wimax/bindings \
build/src/wifi/test \
build/src/wifi/model \
build/src/wifi/helper \
build/src/wifi/examples \
build/src/wifi/bindings \
build/src/wave/test \
build/src/wave/model \
build/src/wave/helper \
build/src/wave/examples \
build/src/wave/bindings \
build/src/visualizer/model \
build/src/visualizer/bindings \
build/src/virtual-net-device/model \
build/src/virtual-net-device/examples \
build/src/virtual-net-device/bindings \
build/src/uan/test \
build/src/uan/model \
build/src/uan/helper \
build/src/uan/examples \
build/src/uan/bindings \
build/src/topology-read/test \
build/src/topology-read/model \
build/src/topology-read/helper \
build/src/topology-read/examples \
build/src/topology-read/bindings \
build/src/test/ns3wifi \
build/src/test/ns3tcp \
build/src/test \
build/src/tap-bridge/model \
build/src/tap-bridge/helper \
build/src/tap-bridge/examples \
build/src/tap-bridge/bindings \
build/src/stats/test \
build/src/stats/model \
build/src/stats/helper \
build/src/stats/examples \
build/src/stats/bindings \
build/src/spectrum/test \
build/src/spectrum/model \
build/src/spectrum/helper \
build/src/spectrum/examples \
build/src/spectrum/bindings \
build/src/sixlowpan/test \
build/src/sixlowpan/model \
build/src/sixlowpan/helper \
build/src/sixlowpan/examples \
build/src/sixlowpan/bindings \
build/src/propagation/test \
build/src/propagation/model \
build/src/propagation/examples \
build/src/propagation/bindings \
build/src/point-to-point-layout/model \
build/src/point-to-point-layout/bindings \
build/src/point-to-point/test \
build/src/point-to-point/model \
build/src/point-to-point/helper \
build/src/point-to-point/examples \
build/src/point-to-point/bindings \
build/src/olsr/test \
build/src/olsr/model \
build/src/olsr/helper \
build/src/olsr/examples \
build/src/olsr/bindings \
build/src/nix-vector-routing/model \
build/src/nix-vector-routing/helper \
build/src/nix-vector-routing/examples \
build/src/nix-vector-routing/bindings \
build/src/network/utils \
build/src/network/test \
build/src/network/model \
build/src/network/helper \
build/src/network/examples \
build/src/network/bindings \
build/src/netanim/test \
build/src/netanim/model \
build/src/netanim/examples \
build/src/mpi/model \
build/src/mpi/examples \
build/src/mpi/bindings \
build/src/mobility/test \
build/src/mobility/model \
build/src/mobility/helper \
build/src/mobility/examples \
build/src/mobility/bindings \
build/src/mesh/test \
build/src/mesh/test/flame \
build/src/mesh/test/dot11s \
build/src/mesh/model \
build/src/mesh/model/flame \
build/src/mesh/model/dot11s \
build/src/mesh/helper \
build/src/mesh/helper/flame \
build/src/mesh/helper/dot11s \
build/src/mesh/examples \
build/src/mesh/bindings \
build/src/lte/test \
build/src/lte/model \
build/src/lte/helper \
build/src/lte/examples \
build/src/lte/bindings \
build/src/lr-wpan/test \
build/src/lr-wpan/model \
build/src/lr-wpan/helper \
build/src/lr-wpan/examples \
build/src/lr-wpan/bindings \
build/src/internet/test \
build/src/internet/model \
build/src/internet/helper \
build/src/internet/examples \
build/src/internet/bindings \
build/src/flow-monitor/test \
build/src/flow-monitor/model \
build/src/flow-monitor/helper \
build/src/flow-monitor/bindings \
build/src/fd-net-device/model \
build/src/fd-net-device/helper \
build/src/fd-net-device/examples \
build/src/fd-net-device/bindings \
build/src/energy/test \
build/src/energy/model \
build/src/energy/helper \
build/src/energy/examples \
build/src/energy/bindings \
build/src/dsr/test \
build/src/dsr/model \
build/src/dsr/helper \
build/src/dsr/examples \
build/src/dsr/bindings \
build/src/dsdv/test \
build/src/dsdv/model \
build/src/dsdv/helper \
build/src/dsdv/examples \
build/src/dsdv/bindings \
build/src/csma-layout/model \
build/src/csma-layout/examples \
build/src/csma-layout/bindings \
build/src/csma/model \
build/src/csma/helper \
build/src/csma/examples \
build/src/csma/bindings \
build/src/core/test \
build/src/core/model \
build/src/core/helper \
build/src/core/examples \
build/src/core/bindings \
build/src/config-store/model \
build/src/config-store/examples \
build/src/config-store/bindings \
build/src/buildings/test \
build/src/buildings/model \
build/src/buildings/helper \
build/src/buildings/examples \
build/src/buildings/bindings \
build/src/bridge/model \
build/src/bridge/helper \
build/src/bridge/examples \
build/src/bridge/bindings \
build/src/applications/test \
build/src/applications/model \
build/src/applications/helper \
build/src/applications/bindings \
build/src/aodv/test \
build/src/aodv/model \
build/src/aodv/helper \
build/src/aodv/examples \
build/src/aodv/bindings \
build/src/antenna/test \
build/src/antenna/model \
build/src/antenna/bindings \
build/scratch/subdir \
build/scratch \
build/examples/wireless \
build/examples/udp-client-server \
build/examples/udp \
build/examples/tutorial \
build/examples/tcp \
build/examples/stats \
build/examples/socket \
build/examples/routing \
build/examples/realtime \
build/examples/naming \
build/examples/matrix-topology \
build/examples/ipv6 \
build/examples/error-model \
build/examples/energy \
build/.conf_check_fe0ca542f39064c5a14ee41a2e983996/testbuild \
build/.conf_check_fe0ca542f39064c5a14ee41a2e983996 \
build/.conf_check_fa0c4ec9c63ac505501cc0863d9bdc48/testbuild \
build/.conf_check_fa0c4ec9c63ac505501cc0863d9bdc48 \
build/.conf_check_f00bb2460dc7019f64c1a347be5879fa/testbuild \
build/.conf_check_f00bb2460dc7019f64c1a347be5879fa \
build/.conf_check_efd20fc635aad783e4d3953701740533/testbuild \
build/.conf_check_efd20fc635aad783e4d3953701740533 \
build/.conf_check_ebd591dbc3bb45aa25214505e9aa0d0f/testbuild \
build/.conf_check_ebd591dbc3bb45aa25214505e9aa0d0f \
build/.conf_check_d8a2c40aecfb7c8eac7dd03fcbfb1110/testbuild \
build/.conf_check_d8a2c40aecfb7c8eac7dd03fcbfb1110 \
build/.conf_check_c94d96928742c001335a0559791a93d8/testbuild \
build/.conf_check_c94d96928742c001335a0559791a93d8 \
build/.conf_check_ace1886511f08627ee2e4ca020806295/testbuild \
build/.conf_check_ace1886511f08627ee2e4ca020806295 \
build/.conf_check_ab7199aa46fcaa2e15071e73776f8218/testbuild \
build/.conf_check_ab7199aa46fcaa2e15071e73776f8218 \
build/.conf_check_97f735b5464546b54ea13ec62d1c17e5/testbuild \
build/.conf_check_97f735b5464546b54ea13ec62d1c17e5 \
build/.conf_check_8dd79274749d59bf459dfbeb1200c7d7/testbuild \
build/.conf_check_8dd79274749d59bf459dfbeb1200c7d7 \
build/.conf_check_8d38681417ac64f5b5b7d4ca87b0e4f3/testbuild \
build/.conf_check_8d38681417ac64f5b5b7d4ca87b0e4f3 \
build/.conf_check_7c67b81911f8bf0aede92c843d0e47cf/testbuild \
build/.conf_check_7c67b81911f8bf0aede92c843d0e47cf \
build/.conf_check_79f849e1774b3cde8897857e178c7c8c/testbuild \
build/.conf_check_79f849e1774b3cde8897857e178c7c8c \
build/.conf_check_6c6255d84543ffa2d8b83c989561eef9/testbuild \
build/.conf_check_6c6255d84543ffa2d8b83c989561eef9 \
build/.conf_check_656b178ce7442053dff90315b31a1cc5 \
build/.conf_check_61ecbfef21667d45a28decabe37fdf64 \
build/.conf_check_5ef57bc0d8aa3565949b6ce1186fd4a7/testbuild \
build/.conf_check_5ef57bc0d8aa3565949b6ce1186fd4a7 \
build/.conf_check_48955ac54d2136a572805353a7b9b62d/testbuild \
build/.conf_check_48955ac54d2136a572805353a7b9b62d \
build/.conf_check_3b2479b91ea1f8aedc2bbc867fa4858e/testbuild \
build/.conf_check_3b2479b91ea1f8aedc2bbc867fa4858e \
build/.conf_check_3a82ef2f96ebcc67f6086c98d2e6291e/testbuild \
build/.conf_check_3a82ef2f96ebcc67f6086c98d2e6291e \
build/.conf_check_355be13189b7b0ddfb123175e2bb33a5 \
build/.conf_check_2be466e82e703a744ee152afe2b58299/testbuild \
build/.conf_check_2be466e82e703a744ee152afe2b58299 \
build/.conf_check_1f933b02106127ce3a9f4633a0e368e7/testbuild \
build/.conf_check_1f933b02106127ce3a9f4633a0e368e7 \
build/.conf_check_0e263e90c2449d9643fa57931cb06d6d/testbuild \
build/.conf_check_0e263e90c2449d9643fa57931cb06d6d \
bindings/python \
OldScratch \

